### ISSUE TITLE
Weekly Plans

### ISSUE THREAD

**Issue by marshtompsxd** [vmware-research/verifiable-controllers#10]
**Mar. 30 - Apr. 13**
- [x] Finish fixing the liveness proof for the simple controller @euclidgame #89 
- [ ] Specify controller crash @marshtompsxd #91 

**Mar. 23 - Mar. 30**
- [x] Build simple controller exec code @marshtompsxd  #82 
- [x] Fix the lemma `after_get_cr_pc ~> []cm_exists` for simple controller @euclidgame #87 
- [ ] Get familiar with the reference zookeeper controller @euclidgame 

**Mar. 16 - Mar. 23**
- [x] Use k8s openapi objects in Kubernetes cluster spec @marshtompsxd  #78 
- [x] Simplify spec by assuming wf on triggering reconcile @marshtompsxd  #79 
- [x] Prove `[]next /\ []fair /\ []exist |= true ~> reconcile_scheduled` @marshtompsxd  #81 
- [x] Fix the lemma `after_create_cm_pc ~> []cm_exists` for simple controller @euclidgame #84 

**Mar. 2 - Mar. 9**
- [x] Specify the controller's list-then-watch behavior #71 
- [x] Layout the k8s openapi objects implementation in both exec and spec mode #74 
- [x] Prove the lemma for unpacking assumptions from spec #75 

**Feb. 23 - Mar. 2**
- [x] Revise the network model for at-most-once delivery #67 
- [x] Revise the network mode to use multiset to preserve duplicated messages #67 

**Feb. 16 - Feb. 23**
- [x] Assign unique id to request/response pairs #65 
- [x] Investigate on the complexity of real-world controllers #66 

**Feb. 9 - Feb. 16**
- [x] Build a simple controller using the Anvil style #62 
- [x] Check how controllers use async/sync k8s API calls #61 #64 
- [ ] Have a list of needed support for exec Map and trait cast from Verus

**Dec. 7 - ... - Feb. 9**
- [x] Complete the simple controller spec (e.g., stream notification, send API request, receive API response) #54 
- [x] Prove the liveness of the simple controller #54 
- [x] Prove the stability of the simple controller #58 
- [x] Implement the generic type for reconciler #60 
- [x] Finish the D-F refactoring for the compound state machine liveness proof #53 

**Nov. 30 - Dec. 7**
- [x] Streamline the action abstraction using the generic Action type #50 
- [x] Rewrite the weak fairness assumptions and enabled proof without the enabled operator #52 
- [ ] Refactor compound state machine proof in the form friendly to LTL engine

**Nov. 23 - Nov. 30**
- [x] Finish reworking the compound state machine #49 
- [ ] Write more complex controller spec

**Nov. 16 - Nov. 23**
- [x] Implement the `next_result` interface of host/network state machine #49 

**Nov. 9 - Nov. 16**
- [x] Rewrite the concurrent controller into a compound state machine #48 
- [x] Prove the safety and liveness property of the compound state machine #48 
- [ ] Collect more real controller reconcile patterns #44 

**Nov. 2 - Nov. 9**
- [x] Fix the liveness property in #45 
- [x] Implement variants of wf1 and leads_to_stable suitable for liveness proof
- [x] Prove all the lemmas except `execution_suffix_xxx` ones #45 

**Oct. 26 - Nov. 2**
- [x] Fix the liveness property and remove any wf assumption on user action #42 
- [x] Document TL lemmas #43 
- [x] Introduce deletion event to the concurrent controller state machine #45 
- [x] Collect real controller reconcile patterns #44 

**Oct. 19 - Oct. 26**
- [x] Reform StatePred/ActionPred from struct to FnSpec #38 
- [x] Clean up the state machine definition (e.g., remove redundant predicates/XXXPred) #37 
- [x] Clean up the liveness proof (e.g., expose the closures in the proof to increase readability) #40 #42 
- [x] Make the concurrent controller more real (e.g., more string operation and less hardcoding) #40 #42

**Oct. 12 - Oct. 19**
- [x] Specify the concurrent controller example #32
- [x] Prove the liveness property of the concurrent controller #32
- [x] Implement universal/existential quantifier for TLA #32 

**Oct. 5 - Oct. 12**
- [x] Address the comments on the temporal logic operator implementation from the meeting #17 #18 #19 #20
- [x] Specify the sequential controller #23  
- [x] Prove the liveness property of the sequential controller #23 

**Sep. 28 - Oct. 5**
- [x] Specify the ABC state machine #11  
- [x] Prove the liveness property of the ABC state machine #11

**Comment by marshtompsxd** [comment]
Close it since everyone knows what to do at this stage
