### ISSUE TITLE
Roadmaps and to-do lists

### ISSUE THREAD

**Issue by marshtompsxd** [vmware-research/verifiable-controllers#133]
### Roadmaps
- [ ] Have a Zookeeper controller implementation that supports creation and update (e.g., scaling, reconfiguration) and verify its liveness by 08/01/2023
- [ ] Specify and prove isolation-related safety properties
- [ ] Have a Rabbitmq controller implementation that supports creation and update and verify its liveness by 09/01/2023
- [ ] Verify deletion operations by 09/01/2023
- [ ] Support non-k8s API calls in controller implementations 10/01/2023
- [ ] Have a third verified controller implementation 10/01/2023

### To-dos
- [ ] Make from_dynamic_object return Result and handle error cases (Major)
- [ ] Make to_dynamic_object return Result and handle error cases (Medium)
- [ ] Refactor DynamicObjectView to split spec and status data (Major)
- [ ] Try out StatefulSetPersistentVolumeClaimRetentionPolicy (Major)
- [ ] Refactor update handling logic to avoid increasing rv if the object remains unchanged (Medium)
- [ ] Make the spec reconciler a trait with safety and liveness proof obligations (Medium)
- [ ] Update the docs (Minor)

... and many more
